httpPort: 8081
wsPort: 8082
metricPort: 9091
appName: GoMahjong
log:
  level: info
  path: ./logs
grpc:
  addr: 127.0.0.1:11500
etcd:
  addrs: ["127.0.0.1:2379"]
  register:
    addr: 127.0.0.1:11500
    name: GoMahjong-1
    version: 0.0.1
    weight: 10
    ttl: 30
database:
  mongo:
    url: mongodb://localhost:27017
    db: go_mahjong
    username: ""
    password: ""
    minPoolSize: 10
    maxPoolSize: 100
  redis:
    addr: localhost:6379
    clusterAddrs: []
    password: ""
    poolSize: 100
    minIdleConns: 10
    host: localhost
    port: 6379
