appName: GoMahjong-gate
metricPort: 9092
httpPort: 8081
log:
  level: debug
  path: ./logs
jwt:
  secret: goMahjong-Secret
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
services:
  connector:
    id: connector-1
    clientHost: 127.0.0.1
    clientPort: 120000
etcd:
  addrs: ["127.0.0.1:2379"]
  register:
    addr: 127.0.0.1:11500
    name: GoMahjong-1
    version: 0.0.1
    weight: 10
    ttl: 30
  rwTimeout: 3
  dialTimeout: 3
